package com.fiserv.jarvis.forms;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import javax.swing.JOptionPane;

/**
 * @author Pelicano, Hector Roman
 */
public class frmConfigB24 extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmConfigB24
     */
    public frmConfigB24() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConfigB24 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJson = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setTitle("Visor Json - Configuración para conexión a B24");
        setName(""); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfigB24.setText("Get Config");
        btnConfigB24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigB24ActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfigB24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, 20));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 90, 20));

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 190, 20));

        txtJson.setBackground(new java.awt.Color(0, 102, 102));
        txtJson.setColumns(20);
        txtJson.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txtJson.setForeground(new java.awt.Color(255, 255, 255));
        txtJson.setRows(5);
        jScrollPane1.setViewportView(txtJson);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String usr = System.getenv("USERNAME");
        
        try {
        
            FileWriter fileWriter = new FileWriter("C:\\Users\\" + usr + "\\Jarvis-config.json");
            fileWriter.write(txtJson.getText());
            fileWriter.flush();
            fileWriter.close();
            JOptionPane.showMessageDialog(null, "Se han guardado los cambios.");
              
        }catch (FileNotFoundException e) {
            System.out.println("No se encontró el archivo.");
            
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
      }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnConfigB24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigB24ActionPerformed
        
        String usr = System.getenv("USERNAME");
        String templateJson =   "{\n" +
                                "    \"User-1DC\": \""+ usr +"\",\n" +
                                "    \"ambientes\": [{\n" +
                                "        \"desarrollo\":{\n" +
                                "            \"user\": \"\",\n" +
                                "            \"pass\": \"\",\n" +
                                "            \"dns\": \"\"\n" +
                                "        }\n" +
                                "    },{\n" +
                                "        \"homologacion\":{\n" +
                                "            \"user\": \"\",\n" +
                                "            \"pass\": \"\",\n" +
                                "            \"dns\": \"\"\n" +
                                "        }\n" +
                                "    },{\n" +
                                "        \"produccion\":{\n" +
                                "            \"user\": \"\",\n" +
                                "            \"pass\": \"\",\n" +
                                "            \"dns\": \"\"\n" +
                                "        }\n" +
                                "    }],\n" +
                                "    \"puertos\":{\n" +
                                "      \"ddls\":7000,\n" +
                                "      \"audit\":7001,\n" +
                                "      \"files\":7002,\n" +
                                "      \"parser\":7003,\n" +
                                "      \"enform\":7004,\n" +
                                "      \"tracker\":7005,\n" +
                                "      \"database\":7006\n" +
                                "    },\n" +
                                "    \"Proyecto\":\"Plataforma Multi-utilitarios para Desarrollo B24\",\n" +
                                "    \"Autor\":\"Pelicano, Hector Roman\",\n" +
                                "}";

        // Leo el archivo de formato JSON
        try {
            File myFile = new File("C:\\Users\\" + usr + "\\Jarvis-config.json");
            if (myFile.createNewFile()) {
                FileWriter fileWriter = new FileWriter("C:\\Users\\" + usr + "\\Jarvis-config.json");
                fileWriter.write(templateJson);
                fileWriter.flush();
                fileWriter.close();
                JOptionPane.showMessageDialog(null, "Se ha creado el archivo de configuración de B24.");
            }
            
            String cadenaJson = new String(Files.readString(myFile.toPath(), StandardCharsets.UTF_8) );
            txtJson.setText(cadenaJson);

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No se ha encontrado el archivo de configuración.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error." + e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_btnConfigB24ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfigB24;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtJson;
    // End of variables declaration//GEN-END:variables
}
