/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.fiserv.jarvis.forms;

/**
 *
 * @author F1W1JF7
 */
public class frmEnform extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEnform
     */
    public frmEnform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecorset = new javax.swing.JTable();
        chkSelect = new javax.swing.JCheckBox();
        chkFrom = new javax.swing.JCheckBox();
        chkWhere = new javax.swing.JCheckBox();
        chkInnerJoin = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        cboxFrom = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSelect = new javax.swing.JList<>();
        cboxJoinItem1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtQuery = new javax.swing.JTextArea();
        cboxWhereItem1 = new javax.swing.JComboBox<>();
        txtWhereItem1 = new javax.swing.JTextField();
        cboxWhereItem2 = new javax.swing.JComboBox<>();
        txtWhereItem2 = new javax.swing.JTextField();
        cboxWhereItem3 = new javax.swing.JComboBox<>();
        txtWhereItem3 = new javax.swing.JTextField();
        chkON = new javax.swing.JCheckBox();
        cboxONInnerJoin = new javax.swing.JComboBox<>();
        cboxEQInnerJoin = new javax.swing.JComboBox<>();
        cboxConditionalItem3 = new javax.swing.JComboBox<>();
        cboxConditionalItem1 = new javax.swing.JComboBox<>();
        cboxConditionalItem2 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstInnerJoin = new javax.swing.JList<>();
        cboxWhereItem4 = new javax.swing.JComboBox<>();
        txtWhereItem4 = new javax.swing.JTextField();
        cboxConditionalItem4 = new javax.swing.JComboBox<>();
        cboxWhereItem5 = new javax.swing.JComboBox<>();
        txtWhereItem5 = new javax.swing.JTextField();
        cboxConditionalItem5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        chkEQ = new javax.swing.JCheckBox();
        btnNewJoin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Enform Query Generator");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRecorset.setAutoCreateRowSorter(true);
        tblRecorset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registros"
            }
        ));
        jScrollPane1.setViewportView(tblRecorset);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 1110, 210));

        chkSelect.setBackground(new java.awt.Color(204, 204, 204));
        chkSelect.setText("SELECT");
        jPanel1.add(chkSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        chkFrom.setBackground(new java.awt.Color(204, 204, 204));
        chkFrom.setText("FROM");
        jPanel1.add(chkFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 70, -1));

        chkWhere.setBackground(new java.awt.Color(204, 204, 204));
        chkWhere.setText("WHERE");
        chkWhere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkWhereActionPerformed(evt);
            }
        });
        jPanel1.add(chkWhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 80, -1));

        chkInnerJoin.setBackground(new java.awt.Color(204, 204, 204));
        chkInnerJoin.setText("INNER JOIN");
        jPanel1.add(chkInnerJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 100, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Query Statement");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 20));

        btnSend.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSend.setForeground(new java.awt.Color(0, 0, 153));
        btnSend.setText("Send");
        jPanel1.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 250, 40));

        jPanel1.add(cboxFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 160, -1));

        jScrollPane2.setViewportView(lstSelect);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 210));

        jPanel1.add(cboxJoinItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 180, -1));

        txtQuery.setColumns(20);
        txtQuery.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtQuery.setForeground(new java.awt.Color(0, 51, 102));
        txtQuery.setLineWrap(true);
        txtQuery.setRows(5);
        txtQuery.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        jScrollPane3.setViewportView(txtQuery);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 730, 90));

        jPanel1.add(cboxWhereItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, -1));
        jPanel1.add(txtWhereItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 150, -1));

        jPanel1.add(cboxWhereItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, -1));
        jPanel1.add(txtWhereItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 150, -1));

        jPanel1.add(cboxWhereItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 130, -1));
        jPanel1.add(txtWhereItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 150, -1));

        chkON.setBackground(new java.awt.Color(204, 204, 204));
        chkON.setText("ON");
        jPanel1.add(chkON, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        jPanel1.add(cboxONInnerJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 180, -1));

        jPanel1.add(cboxEQInnerJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 180, -1));

        cboxConditionalItem3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "AND", "OR", "MAYOR", "MINOR", "EQUAL", "LIKE" }));
        jPanel1.add(cboxConditionalItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        cboxConditionalItem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "AND", "OR", "MAYOR", "MINOR", "EQUAL", "LIKE" }));
        jPanel1.add(cboxConditionalItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        cboxConditionalItem2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "AND", "OR", "MAYOR", "MINOR", "EQUAL", "LIKE" }));
        jPanel1.add(cboxConditionalItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jScrollPane4.setViewportView(lstInnerJoin);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 210, 190));

        jPanel1.add(cboxWhereItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 130, -1));
        jPanel1.add(txtWhereItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 150, -1));

        cboxConditionalItem4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "AND", "OR", "MAYOR", "MINOR", "EQUAL", "LIKE" }));
        jPanel1.add(cboxConditionalItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jPanel1.add(cboxWhereItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 130, -1));
        jPanel1.add(txtWhereItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 150, -1));

        cboxConditionalItem5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "AND", "OR", "MAYOR", "MINOR", "EQUAL", "LIKE" }));
        jPanel1.add(cboxConditionalItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("<< Choose Main File first.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 170, 20));

        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 250));

        btnCreate.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 102, 255));
        btnCreate.setText("Create Query");
        jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 50));

        btnReset.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 120, 40));

        btnPdf.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        btnPdf.setForeground(new java.awt.Color(255, 0, 0));
        btnPdf.setText("Export PDF");
        jPanel1.add(btnPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 120, 40));

        chkEQ.setBackground(new java.awt.Color(204, 204, 204));
        chkEQ.setText("EQ");
        jPanel1.add(chkEQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        btnNewJoin.setText("New Join");
        jPanel1.add(btnNewJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 420, -1));

        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 440, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkWhereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWhereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWhereActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnNewJoin;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSend;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboxConditionalItem1;
    private javax.swing.JComboBox<String> cboxConditionalItem2;
    private javax.swing.JComboBox<String> cboxConditionalItem3;
    private javax.swing.JComboBox<String> cboxConditionalItem4;
    private javax.swing.JComboBox<String> cboxConditionalItem5;
    private javax.swing.JComboBox<String> cboxEQInnerJoin;
    private javax.swing.JComboBox<String> cboxFrom;
    private javax.swing.JComboBox<String> cboxJoinItem1;
    private javax.swing.JComboBox<String> cboxONInnerJoin;
    private javax.swing.JComboBox<String> cboxWhereItem1;
    private javax.swing.JComboBox<String> cboxWhereItem2;
    private javax.swing.JComboBox<String> cboxWhereItem3;
    private javax.swing.JComboBox<String> cboxWhereItem4;
    private javax.swing.JComboBox<String> cboxWhereItem5;
    private javax.swing.JCheckBox chkEQ;
    private javax.swing.JCheckBox chkFrom;
    private javax.swing.JCheckBox chkInnerJoin;
    private javax.swing.JCheckBox chkON;
    private javax.swing.JCheckBox chkSelect;
    private javax.swing.JCheckBox chkWhere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstInnerJoin;
    private javax.swing.JList<String> lstSelect;
    private javax.swing.JTable tblRecorset;
    private javax.swing.JTextArea txtQuery;
    private javax.swing.JTextField txtWhereItem1;
    private javax.swing.JTextField txtWhereItem2;
    private javax.swing.JTextField txtWhereItem3;
    private javax.swing.JTextField txtWhereItem4;
    private javax.swing.JTextField txtWhereItem5;
    // End of variables declaration//GEN-END:variables
}
