/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fiserv.jarvis.forms;

import javax.swing.JDialog;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author F1W1JF7
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        
        try{
            
            frmPrincipal.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName() );
            
        }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e){
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        dskPaneConteiner = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuItemConfig = new javax.swing.JMenuItem();
        mnuItemDB = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuItemSalir = new javax.swing.JMenuItem();
        mnuFiles = new javax.swing.JMenu();
        mnuItemPtd = new javax.swing.JMenuItem();
        mnuTools = new javax.swing.JMenu();
        mnuItemLibs = new javax.swing.JMenuItem();
        mnuItemAuditViewer = new javax.swing.JMenuItem();
        mnuItemEnform = new javax.swing.JMenuItem();
        mnuItemParser = new javax.swing.JMenuItem();
        mnuItemTerminalSSH = new javax.swing.JMenuItem();
        mnuTest = new javax.swing.JMenu();
        mnuItemUnitTest = new javax.swing.JMenuItem();
        mnuItemTestEditor = new javax.swing.JMenuItem();
        mnuTracker = new javax.swing.JMenu();
        mnuItemFinder = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuItemAuditHelp = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("“Just a Really Very Intelligent System”");

        javax.swing.GroupLayout dskPaneConteinerLayout = new javax.swing.GroupLayout(dskPaneConteiner);
        dskPaneConteiner.setLayout(dskPaneConteinerLayout);
        dskPaneConteinerLayout.setHorizontalGroup(
            dskPaneConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1357, Short.MAX_VALUE)
        );
        dskPaneConteinerLayout.setVerticalGroup(
            dskPaneConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        mnuInicio.setText("Inicio");

        mnuItemConfig.setText("Config Users B24");
        mnuItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConfigActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuItemConfig);

        mnuItemDB.setText("DataBase");
        mnuItemDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDBActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuItemDB);

        jMenuItem4.setText("Export Statistics (.xls)");
        mnuInicio.add(jMenuItem4);
        mnuInicio.add(jSeparator1);

        mnuItemSalir.setText("Salir");
        mnuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSalirActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuItemSalir);

        jMenuBar1.add(mnuInicio);

        mnuFiles.setText("Files");

        mnuItemPtd.setText("Viewer");
        mnuFiles.add(mnuItemPtd);

        jMenuBar1.add(mnuFiles);

        mnuTools.setText("Tools");

        mnuItemLibs.setText("Library Manager");
        mnuItemLibs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLibsActionPerformed(evt);
            }
        });
        mnuTools.add(mnuItemLibs);

        mnuItemAuditViewer.setText("Audit Viewer");
        mnuItemAuditViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAuditViewerActionPerformed(evt);
            }
        });
        mnuTools.add(mnuItemAuditViewer);

        mnuItemEnform.setText("Enform");
        mnuItemEnform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEnformActionPerformed(evt);
            }
        });
        mnuTools.add(mnuItemEnform);

        mnuItemParser.setText("Parser");
        mnuItemParser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemParserActionPerformed(evt);
            }
        });
        mnuTools.add(mnuItemParser);

        mnuItemTerminalSSH.setText("Terminal SSH");
        mnuItemTerminalSSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemTerminalSSHActionPerformed(evt);
            }
        });
        mnuTools.add(mnuItemTerminalSSH);

        jMenuBar1.add(mnuTools);

        mnuTest.setText("Test");

        mnuItemUnitTest.setText("Test Manager");
        mnuItemUnitTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemUnitTestActionPerformed(evt);
            }
        });
        mnuTest.add(mnuItemUnitTest);

        mnuItemTestEditor.setText("Test Editor");
        mnuItemTestEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemTestEditorActionPerformed(evt);
            }
        });
        mnuTest.add(mnuItemTestEditor);

        jMenuBar1.add(mnuTest);

        mnuTracker.setText("Tracker");

        mnuItemFinder.setText("Tx Finder");
        mnuItemFinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemFinderActionPerformed(evt);
            }
        });
        mnuTracker.add(mnuItemFinder);

        jMenuBar1.add(mnuTracker);

        mnuHelp.setText("Help");

        mnuItemAuditHelp.setText("Audit");
        mnuItemAuditHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAuditHelpActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuItemAuditHelp);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPaneConteiner)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPaneConteiner)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConfigActionPerformed
        frmConfigB24 frmB24 =new frmConfigB24();
        this.dskPaneConteiner.add(frmB24).setVisible(true);
    }//GEN-LAST:event_mnuItemConfigActionPerformed

    private void mnuItemDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDBActionPerformed
        
        frmDataBase db =new frmDataBase();
        this.dskPaneConteiner.add(db).setVisible(true);
        
        
    }//GEN-LAST:event_mnuItemDBActionPerformed

    private void mnuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_mnuItemSalirActionPerformed

    private void mnuItemLibsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLibsActionPerformed
        frmLibraryManager frmLM =new frmLibraryManager();
        this.dskPaneConteiner.add(frmLM).setVisible(true);
    }//GEN-LAST:event_mnuItemLibsActionPerformed

    private void mnuItemTerminalSSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemTerminalSSHActionPerformed
        frmTerminalSSH frmAC =new frmTerminalSSH();
        this.dskPaneConteiner.add(frmAC).setVisible(true);
    }//GEN-LAST:event_mnuItemTerminalSSHActionPerformed

    private void mnuItemAuditHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAuditHelpActionPerformed
        frmAuditHelp frmAH =new frmAuditHelp();
        this.dskPaneConteiner.add(frmAH).setVisible(true);
    }//GEN-LAST:event_mnuItemAuditHelpActionPerformed

    private void mnuItemAuditViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAuditViewerActionPerformed
        frmAuditViewer frmAV =new frmAuditViewer();
        this.dskPaneConteiner.add(frmAV).setVisible(true);
    }//GEN-LAST:event_mnuItemAuditViewerActionPerformed

    private void mnuItemParserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemParserActionPerformed
        frmParser frmP =new frmParser();
        this.dskPaneConteiner.add(frmP).setVisible(true);
    }//GEN-LAST:event_mnuItemParserActionPerformed

    private void mnuItemEnformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEnformActionPerformed
        frmEnform frmE =new frmEnform();
        this.dskPaneConteiner.add(frmE).setVisible(true);
    }//GEN-LAST:event_mnuItemEnformActionPerformed

    private void mnuItemUnitTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUnitTestActionPerformed
        frmTestManager frmTM =new frmTestManager();
        this.dskPaneConteiner.add(frmTM).setVisible(true);
    }//GEN-LAST:event_mnuItemUnitTestActionPerformed

    private void mnuItemFinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemFinderActionPerformed
        frmTxFinder frmTF =new frmTxFinder();
        this.dskPaneConteiner.add(frmTF).setVisible(true);
    }//GEN-LAST:event_mnuItemFinderActionPerformed

    private void mnuItemTestEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemTestEditorActionPerformed
        frmTestEditor frmTE =new frmTestEditor();
        this.dskPaneConteiner.add(frmTE).setVisible(true);
    }//GEN-LAST:event_mnuItemTestEditorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPaneConteiner;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuFiles;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenuItem mnuItemAuditHelp;
    private javax.swing.JMenuItem mnuItemAuditViewer;
    private javax.swing.JMenuItem mnuItemConfig;
    private javax.swing.JMenuItem mnuItemDB;
    private javax.swing.JMenuItem mnuItemEnform;
    private javax.swing.JMenuItem mnuItemFinder;
    private javax.swing.JMenuItem mnuItemLibs;
    private javax.swing.JMenuItem mnuItemParser;
    private javax.swing.JMenuItem mnuItemPtd;
    private javax.swing.JMenuItem mnuItemSalir;
    private javax.swing.JMenuItem mnuItemTerminalSSH;
    private javax.swing.JMenuItem mnuItemTestEditor;
    private javax.swing.JMenuItem mnuItemUnitTest;
    private javax.swing.JMenu mnuTest;
    private javax.swing.JMenu mnuTools;
    private javax.swing.JMenu mnuTracker;
    // End of variables declaration//GEN-END:variables
}
