/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.fiserv.jarvis.forms;

/**
 *
 * @author F1W1JF7
 */
public class frmTestManager extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmTestManager
     */
    public frmTestManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeTestFiles = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResults = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLoguer = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstProcess = new javax.swing.JList<>();
        rbtnUnitTest = new javax.swing.JRadioButton();
        btnStart = new javax.swing.JButton();
        rbtnMultiTest = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rbtnDvlp = new javax.swing.JRadioButton();
        rbtnTest = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Test Cases Manager ACQ / ISS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true), "Load Hexa Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 204))); // NOI18N
        jTextPane1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 102, 204));
        jScrollPane2.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 410, 480));

        jButton1.setText("Save File");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 40));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true), "File Name:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Test Files Library Collection");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 610));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        treeTestFiles.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 3, true), "Local Test Files", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 0, 0))); // NOI18N
        jScrollPane1.setViewportView(treeTestFiles);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 310));

        tblResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Test Date", "Case Namber", "Status", "Sequence Number", "Resp Code", "Elapse Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblResults);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 890, 260));

        txtLoguer.setEditable(false);
        txtLoguer.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 3, true), "Loguer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 0, 0))); // NOI18N
        txtLoguer.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(txtLoguer);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 290, 310));

        lstProcess.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true), "Process List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 153, 0))); // NOI18N
        lstProcess.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lstProcess);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 210, 310));

        rbtnUnitTest.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(rbtnUnitTest);
        rbtnUnitTest.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rbtnUnitTest.setForeground(new java.awt.Color(255, 255, 255));
        rbtnUnitTest.setText("Unit Test");
        rbtnUnitTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnUnitTestActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnUnitTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 100, -1));

        btnStart.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(204, 0, 0));
        btnStart.setText("Start Test");
        jPanel2.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 100, 80));

        rbtnMultiTest.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(rbtnMultiTest);
        rbtnMultiTest.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rbtnMultiTest.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMultiTest.setText("Multi-Test");
        jPanel2.add(rbtnMultiTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 110, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true), "Test Cases", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 140, 90));

        rbtnDvlp.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup2.add(rbtnDvlp);
        rbtnDvlp.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rbtnDvlp.setForeground(new java.awt.Color(255, 255, 255));
        rbtnDvlp.setText("DVLP");
        jPanel2.add(rbtnDvlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 80, -1));

        rbtnTest.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup2.add(rbtnTest);
        rbtnTest.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rbtnTest.setForeground(new java.awt.Color(255, 255, 255));
        rbtnTest.setText("TEST");
        jPanel2.add(rbtnTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 70, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true), "Enviroment:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 140, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 910, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnUnitTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnUnitTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnUnitTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JList<String> lstProcess;
    private javax.swing.JRadioButton rbtnDvlp;
    private javax.swing.JRadioButton rbtnMultiTest;
    private javax.swing.JRadioButton rbtnTest;
    private javax.swing.JRadioButton rbtnUnitTest;
    private javax.swing.JTable tblResults;
    private javax.swing.JTree treeTestFiles;
    private javax.swing.JTextPane txtLoguer;
    // End of variables declaration//GEN-END:variables
}
