package com.fiserv.jarvis.forms;


import com.fiserv.jarvis.libShellSSH.SSHConnection;
import com.fiserv.jarvis.utils.Utils;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * @author F1W1JF7
 */
public class frmTerminalSSH extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAudit
     */
    public frmTerminalSSH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAudit = new javax.swing.ButtonGroup();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtComando = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtShell = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        txtFilename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbtnExplode = new javax.swing.JRadioButton();
        rbtnNetadrd = new javax.swing.JRadioButton();
        cboxListaComandos = new javax.swing.JComboBox<>();
        rbtnManual = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        jTextField6.setText("jTextField6");

        setClosable(true);
        setIconifiable(true);
        setTitle("Audit Visor B24");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtComando.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtComando.setForeground(new java.awt.Color(255, 0, 0));
        txtComando.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true), "Command Line:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 204))); // NOI18N
        txtComando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComandoKeyPressed(evt);
            }
        });
        jPanel2.add(txtComando, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 530, 50));

        txtShell.setEditable(false);
        txtShell.setColumns(20);
        txtShell.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtShell.setRows(5);
        txtShell.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        jScrollPane2.setViewportView(txtShell);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 980, 490));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 30));
        jPanel2.add(txtFilename, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true), "Save File:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 110));

        rbtnExplode.setBackground(new java.awt.Color(0, 0, 0));
        btnGroupAudit.add(rbtnExplode);
        rbtnExplode.setForeground(new java.awt.Color(255, 255, 255));
        rbtnExplode.setText("Explode");
        jPanel2.add(rbtnExplode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        rbtnNetadrd.setBackground(new java.awt.Color(0, 0, 0));
        btnGroupAudit.add(rbtnNetadrd);
        rbtnNetadrd.setForeground(new java.awt.Color(255, 255, 255));
        rbtnNetadrd.setText("Netadrd");
        jPanel2.add(rbtnNetadrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        cboxListaComandos.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        cboxListaComandos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>" }));
        cboxListaComandos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true), "History:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        cboxListaComandos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxListaComandosItemStateChanged(evt);
            }
        });
        jPanel2.add(cboxListaComandos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 440, 50));

        rbtnManual.setBackground(new java.awt.Color(0, 0, 0));
        btnGroupAudit.add(rbtnManual);
        rbtnManual.setForeground(new java.awt.Color(255, 255, 255));
        rbtnManual.setText("Manual");
        jPanel2.add(rbtnManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Format:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String propertyPath = null ;
        
        propertyPath = Utils.getProperty(propertyFile, "directory.root.Audit");
        
        String fileName = propertyPath + "\\\\" + txtFilename.getText() + ".txt";
        
        if(!Utils.checkFileOrDirectory(fileName)){
            if(Utils.createFile(fileName)==1){
                if(Utils.saveFile(fileName, txtShell.getText())){
                    JOptionPane.showMessageDialog(null,"El archivo [" + fileName + " ] se guardado exitosamente." );
                }else{
                    JOptionPane.showMessageDialog(null,"Error al guardar el archivo [" + fileName + " ]." );
                }
            }else if(Utils.createFile(fileName)==0){
                JOptionPane.showMessageDialog(null,"El archivo [" + fileName + " ] ya existe." );

            }else{
                JOptionPane.showMessageDialog(null,"Error al Crear el archivo [" + fileName + " ]." );
            }
        }else{
            JOptionPane.showMessageDialog(null,"El archivo ya existe !!!." );
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       
        String host = Utils.getProperty( propertyFile , "config_env.desarrollo.dns");
        String user = Utils.getProperty( propertyFile , "config_env.desarrollo.user");
        String pass = Utils.getProperty( propertyFile , "config_env.desarrollo.pass");
        int port = Integer.parseInt(Utils.getProperty( propertyFile , "config_port.ssh"));
        
        rbtnManual.setSelected(true);
        
        connection = new SSHConnection(host, user, pass);
        connection.connect();
        connection.startShellSession(s -> {
            txtShell.append(s);
            return null;
        });
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtComandoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComandoKeyPressed
        
        String comando;
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if(rbtnExplode.isSelected()){
                comando = "gtacl -p /G/data26/dvlputil/explode '" + txtComando.getText()+ "'" ;
            }else if(rbtnNetadrd.isSelected()){
                comando = "gtacl -p /G/data17/xpnet/netadrd '" + txtComando.getText()+ "'" ;
            }else{
                comando = txtComando.getText();
            }
            
            connection.writeShellMessage(comando);
            //connection.writeShellMessage(txtComando.getText());
            txtComando.setText("");
            
            GuardarEnHistorial(comando);
            
        }
    }//GEN-LAST:event_txtComandoKeyPressed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        connection.disconnect();
        JOptionPane.showMessageDialog(null, "Se ha cerrado la Session con el Tandem.");
    }//GEN-LAST:event_formInternalFrameClosed

    private void cboxListaComandosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxListaComandosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //System.out.println("Ha seleccionado el item: " + cboxListaComandos.getSelectedItem().toString());
            
            txtComando.setText(cboxListaComandos.getSelectedItem().toString());
            
        }
    }//GEN-LAST:event_cboxListaComandosItemStateChanged

    private void GuardarEnHistorial(String comando){
        cboxListaComandos.addItem(comando);
    }
    
    
    
    SSHConnection connection = null;
    private static String propertyFile = "C:\\Jarvis\\Config\\Properties";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupAudit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboxListaComandos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JRadioButton rbtnExplode;
    private javax.swing.JRadioButton rbtnManual;
    private javax.swing.JRadioButton rbtnNetadrd;
    private javax.swing.JTextField txtComando;
    private javax.swing.JTextField txtFilename;
    private javax.swing.JTextArea txtShell;
    // End of variables declaration//GEN-END:variables
}
